kind: dingofs
container_image: dingodatabase/dingofs:latest
mdsOpt.rpcRetryOpt.addrs: 10.0.1.1:6700,10.0.1.2:6700,10.0.1.3:6700
log_dir: ${home}/dingofs/logs/client

### if fstype is s3
s3.ak: <>
s3.sk: <>
s3.endpoint: <>
s3.bucket_name: <>
