kind: dingofs
global:
  report_usage: false
  container_image: dingodatabase/dingofs:latest
  log_dir: /mnt/disk${service_replica_sequence}/dingofs/logs/${service_role}
  data_dir: /mnt/disk${service_replica_sequence}/dingofs/data/${service_role}
  variable:
    machine1: server-host1
    machine2: server-host2
    machine3: server-host3

etcd_services:
  config:
    listen.ip: ${service_host}
    listen.port: 12380
    listen.client_port: 12379
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

mds_services:
  config:
    listen.ip: ${service_host}
    listen.port: 6700
    listen.dummy_port: 7700
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}

metaserver_services:
  config:
    listen.ip: ${service_host}
    listen.port: 680${service_replica_sequence}
    listen.external_port: 780${service_replica_sequence}
    metaserver.loglevel: 0
  deploy:
    - host: ${machine1}
      replicas: 3
    - host: ${machine2}
      replicas: 3
    - host: ${machine3}
      replicas: 3