kind: dingofs
global:
  report_usage: true
  data_dir: ${home}/dingofs/data/${service_role}
  log_dir: ${home}/dingofs/logs/${service_role}
  container_image: dingodatabase/dingofs:latest
  variable:
    home: /tmp
    machine1: server-host1
    machine2: serevr-host2
    machine3: server-host3

mds_services:
  config:
    listen.ip: ${service_host}
    listen.port: 6700
    listen.dummy_port: 7700
  deploy:
    - host: ${machine1}
    - host: ${machine2}
    - host: ${machine3}
