kind: dingofs
global:
  container_image: harbor.zetyun.cn/dingofs/dingofs:v2
  coordinator_addr: 10.225.10.50:6500,10.225.10.51:6500,10.225.10.52:6500
  log_dir: ${home}/dingofs/logs/${service_role}
  variable:
    home: /tmp
    machine1: server-host1
    machine2: server-host2
    machine3: server-host3

mdsv2_services:
  config:
    server.port: 6900
  deploy:
    - host: ${machine1}
      config:
        instance_start_id: 1001
    - host: ${machine2}
      config:
        instance_start_id: 1002
    - host: ${machine3}
      config:
        instance_start_id: 1003
